spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tP3VgUxMutpUUZb7UDM
      secret-key: Ic94qHuhFeuHhn2o4z3IYEtODqfGhN
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: gulimallyuanstudy

  application:
    name: gulimall-third-party

server:
  port: 30000
